web server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,8 +1,16 @@
-#!/usr/bin/env bash
-# nginx web server listening on port 80
-# returns a page that contains the string "Hello World!"
+#!/bin/bash
+# Update package list
+# change listening port to 80 and output hello world in htm
+sudo apt update
+sudo apt install nginx -y
+sudo sed -i 's/listen \[::\]:80 default_server;/listen 80;/' /etc/nginx/sites-available/default
+sudo service nginx restart
+sudo echo "Hello World!" | sudo tee /var/www/html/index.html
+curl http://localhost:80 | grep "Hello World!" >/dev/null
 
-sudo apt update -y
-sudo apt install -y nginx
-echo 'Hello World!' > /var/www/html/index.nginx-debian.html
-sudo service nginx start
+if [ $? -eq 0 ]
+then
+  echo "Nginx installed and configured successfully!"
+else
+  echo "Nginx installation or configuration failed!"
+fi
